function eqs = cartpoleDAEFunction(t,in2,in3,param98,param99,param100,param101,param102,param103,param104)
%cartpoleDAEFunction
%    EQS = cartpoleDAEFunction(T,IN2,IN3,PARAM98,PARAM99,PARAM100,PARAM101,PARAM102,PARAM103,PARAM104)

%    This function was generated by the Symbolic Math Toolbox version 9.0.
%    26-Jan-2023 10:35:22

Dthetat = in2(5,:);
Dxt = in2(4,:);
Nc = in2(3,:);
YP56 = in3(1,:);
YP57 = in3(2,:);
YP59 = in3(4,:);
YP60 = in3(5,:);
theta = in2(2,:);
t2 = sign(Dxt);
t3 = sign(Nc);
t4 = cos(theta);
t5 = sin(theta);
t6 = param101+param102;
t7 = Dthetat.^2;
t8 = 1.0./param100;
t9 = 1.0./t6;
eqs = [Nc.*1.0e+3-param99.*t6+param100.*param102.*(YP60.*t5+t4.*t7);YP60-(t8.*(-param99.*t5+t4.*(t9.*(param98+param100.*param102.*t7.*(t5+param103.*t2.*t3.*t4))-param99.*param103.*t2.*t3)+(Dthetat.*param104.*t8)./param102))./(param102.*t4.*t9.*(t4-param103.*t2.*t3)-4.0./3.0);YP59+t9.*(-param98+param100.*param102.*(YP60.*t4-t5.*t7)+Nc.*param103.*t2.*t3.*1.0e+3);Dxt-YP56;Dthetat-YP57];
