function eqs = cartpoleDAEFunction(t,in2,in3,param226,param227,param228,param229,param230,param231,param232)
%cartpoleDAEFunction
%    EQS = cartpoleDAEFunction(T,IN2,IN3,PARAM226,PARAM227,PARAM228,PARAM229,PARAM230,PARAM231,PARAM232)

%    This function was generated by the Symbolic Math Toolbox version 9.0.
%    25-Jan-2023 15:09:40

Dthetat = in2(5,:);
Dxt = in2(4,:);
Nc = in2(3,:);
YP136 = in3(1,:);
YP137 = in3(2,:);
YP139 = in3(4,:);
YP140 = in3(5,:);
theta = in2(2,:);
t2 = sign(Dxt);
t3 = sign(Nc);
t4 = cos(theta);
t5 = sin(theta);
t6 = param229+param230;
t7 = Dthetat.^2;
t8 = 1.0./param228;
t9 = 1.0./t6;
eqs = [Nc.*1.0e+3-param227.*t6+param228.*param230.*(YP140.*t5+t4.*t7);YP140-(t8.*(-param227.*t5+t4.*(t9.*(param226+param228.*param230.*t7.*(t5+param231.*t2.*t3.*t4))-param227.*param231.*t2.*t3)+(Dthetat.*param232.*t8)./param230))./(param230.*t4.*t9.*(t4-param231.*t2.*t3)-4.0./3.0);YP139+t9.*(-param226+param228.*param230.*(YP140.*t4-t5.*t7)+Nc.*param231.*t2.*t3.*1.0e+3);Dxt-YP136;Dthetat-YP137];
