function eqs = craneDAEFunction(t,in2,in3,param290,param291,param292,param293,param294,param295,param296,param297,param298)
%craneDAEFunction
%    EQS = craneDAEFunction(T,IN2,IN3,PARAM290,PARAM291,PARAM292,PARAM293,PARAM294,PARAM295,PARAM296,PARAM297,PARAM298)

%    This function was generated by the Symbolic Math Toolbox version 9.0.
%    25-Jan-2023 15:28:05

Dthetat = in2(5,:);
Dxt = in2(4,:);
Nc = in2(3,:);
YP176 = in3(1,:);
YP177 = in3(2,:);
YP179 = in3(4,:);
YP180 = in3(5,:);
theta = in2(2,:);
t2 = sign(Dxt);
t3 = sign(Nc);
t4 = cos(theta);
t5 = sin(theta);
t6 = param294+param295;
t7 = Dthetat.^2;
t8 = 1.0./t6;
eqs = [Nc.*1.0e+3-param293.*t6+param291.*param295.*(YP180.*t5+t4.*t7);YP180-(-param293.*t5+t4.*(t8.*(param290+param291.*param295.*t7.*(t5+param296.*t2.*t3.*t4))-param293.*param296.*t2.*t3)+(param291.^2.*param292.*param297.^2.*param298.*t7.*1.550313834014991e+1)./param295)./(param291.*(param295.*t4.*t8.*(t4-param296.*t2.*t3)-4.0./3.0));YP179+t8.*(-param290+param291.*param295.*(YP180.*t4-t5.*t7)+Nc.*param296.*t2.*t3.*1.0e+3);Dxt-YP176;Dthetat-YP177];
