function eqs = craneDAEFunction(t,in2,in3,param118,param119,param120,param121,param122,param123,param124,param125,param126)
%craneDAEFunction
%    EQS = craneDAEFunction(T,IN2,IN3,PARAM118,PARAM119,PARAM120,PARAM121,PARAM122,PARAM123,PARAM124,PARAM125,PARAM126)

%    This function was generated by the Symbolic Math Toolbox version 9.0.
%    13-Feb-2023 15:37:29

Dthetat = in2(11,:);
Dxt = in2(10,:);
F_d = in2(5,:);
F_f = in2(4,:);
N_c = in2(3,:);
N_x = in2(6,:);
N_y = in2(7,:);
YP144 = in3(1,:);
YP145 = in3(2,:);
YP153 = in3(10,:);
YP154 = in3(11,:);
theta = in2(2,:);
v_x = in2(8,:);
v_y = in2(9,:);
t2 = cos(theta);
t3 = sin(theta);
t4 = Dthetat.^2;
t5 = param125.^2;
t6 = v_x.^2;
t7 = v_y.^2;
eqs = [-Dxt+v_x-Dthetat.*param119.*t2;v_y-Dthetat.*param119.*t3;F_d-(param120.*param126.*t5.*pi.*(t6+t7))./2.0;N_x-param123.*(YP153+YP154.*param119.*t2-param119.*t3.*t4);N_y-param123.*(param121-param119.*(YP154.*t3+t2.*t4));N_c-N_y-param121.*param122;F_f-N_c.*param124.*sign(Dxt.*N_c);YP153+(F_f-param118+param119.*param123.*(YP154.*t2-t3.*t4))./(param122+param123);YP154+((t2.*(YP153.*param123+(param120.*param126.*t5.*t6.*pi.*sign(v_x))./2.0)-t3.*(param121.*param123-(param120.*param126.*t5.*t7.*pi.*sign(v_y))./2.0)).*(3.0./4.0))./(param119.*param123);Dxt-YP144;Dthetat-YP145];
