function eqs = craneDAEFunction(t,in2,in3,param325,param326,param327,param328,param329,param330,param331,param332,param333)
%craneDAEFunction
%    EQS = craneDAEFunction(T,IN2,IN3,PARAM325,PARAM326,PARAM327,PARAM328,PARAM329,PARAM330,PARAM331,PARAM332,PARAM333)

%    This function was generated by the Symbolic Math Toolbox version 9.0.
%    28-Jan-2023 16:14:36

Dthetat = in2(7,:);
Dxt = in2(6,:);
F_d = in2(5,:);
F_f = in2(4,:);
N_c = in2(3,:);
YP243 = in3(1,:);
YP244 = in3(2,:);
YP248 = in3(6,:);
YP249 = in3(7,:);
theta = in2(2,:);
t2 = cos(theta);
t3 = sin(theta);
t4 = param329+param330;
t5 = Dthetat.^2;
t6 = Dxt.^2;
t7 = param332.^2;
t10 = Dthetat.*param326.*pi;
t12 = -param325;
t8 = t3.^2;
t9 = t3.^3;
t11 = Dxt.*t2;
t13 = 1.0./t4;
t14 = t10+t11;
t16 = (param327.*param333.*t6.*t7.*t9.*pi)./2.0;
t15 = t14.^2;
eqs = [N_c-param328.*t4+param326.*param330.*(YP249.*t3+t2.*t5)-(param327.*param333.*t2.*t6.*t7.*t8.*pi)./2.0;F_f-N_c.*param331.*sign(Dxt.*N_c);F_d-(param327.*param333.*t7.*pi.*(t15+t6.*t8))./2.0;YP249+(param328.*t3+t2.*t13.*(F_f+t12+t16-param326.*param330.*t3.*t5)-(param327.*param333.*t7.*t15.*pi)./(param330.*2.0))./(param326.*(param330.*t2.^2.*t13-4.0./3.0));YP248+t13.*(F_f+t12+t16+param326.*param330.*(YP249.*t2-t3.*t5));Dxt-YP243;Dthetat-YP244];
