function eqs = cartpoleDAEFunction(t,in2,in3,param247,param248,param249,param250,param251,param252,param253)
%cartpoleDAEFunction
%    EQS = cartpoleDAEFunction(T,IN2,IN3,PARAM247,PARAM248,PARAM249,PARAM250,PARAM251,PARAM252,PARAM253)

%    This function was generated by the Symbolic Math Toolbox version 9.0.
%    25-Jan-2023 15:13:01

Dthetat = in2(5,:);
Dxt = in2(4,:);
Nc = in2(3,:);
YP151 = in3(1,:);
YP152 = in3(2,:);
YP154 = in3(4,:);
YP155 = in3(5,:);
theta = in2(2,:);
t2 = sign(Dxt);
t3 = sign(Nc);
t4 = cos(theta);
t5 = sin(theta);
t6 = param250+param251;
t7 = Dthetat.^2;
t8 = 1.0./param249;
t9 = 1.0./t6;
eqs = [Nc.*1.0e+3-param248.*t6+param249.*param251.*(YP155.*t5+t4.*t7);YP155-(t8.*(-param248.*t5+t4.*(t9.*(param247+param249.*param251.*t7.*(t5+param252.*t2.*t3.*t4))-param248.*param252.*t2.*t3)+(Dthetat.*param253.*t8)./param251))./(param251.*t4.*t9.*(t4-param252.*t2.*t3)-4.0./3.0);YP154+t9.*(-param247+param249.*param251.*(YP155.*t4-t5.*t7)+Nc.*param252.*t2.*t3.*1.0e+3);Dxt-YP151;Dthetat-YP152];
