function eqs = cartpoleDAEFunction(t,in2,in3,param204,param205,param206,param207,param208,param209,param210)
%cartpoleDAEFunction
%    EQS = cartpoleDAEFunction(T,IN2,IN3,PARAM204,PARAM205,PARAM206,PARAM207,PARAM208,PARAM209,PARAM210)

%    This function was generated by the Symbolic Math Toolbox version 9.0.
%    22-Jan-2023 17:59:20

Dthetat = in2(5,:);
Dxt = in2(4,:);
Nc = in2(3,:);
YP146 = in3(1,:);
YP147 = in3(2,:);
YP149 = in3(4,:);
YP150 = in3(5,:);
theta = in2(2,:);
t2 = cos(theta);
t3 = sin(theta);
t4 = param207+param208;
t5 = Dthetat.^2;
t6 = Dxt.*Nc;
t8 = 1.0./param206;
t7 = sign(t6);
t9 = 1.0./t4;
eqs = [Nc.*1.0e+3-param205.*t4+param206.*param208.*(YP150.*t3+t2.*t5);YP150-(t8.*(-param205.*t3+t2.*(t9.*(param204+param206.*param208.*t5.*(t3+param209.*t2.*t7))-param205.*param209.*t7)+(Dthetat.*param210.*t8)./param208))./(param208.*t2.*t9.*(t2-param209.*t7)-4.0./3.0);YP149+t9.*(-param204+param206.*param208.*(YP150.*t2-t3.*t5)+Nc.*param209.*t7.*1.0e+3);Dxt-YP146;Dthetat-YP147];
