function eqs = cartpoleDAEFunction(t,in2,in3,param120,param121,param122,param123,param124,param125,param126)
%cartpoleDAEFunction
%    EQS = cartpoleDAEFunction(T,IN2,IN3,PARAM120,PARAM121,PARAM122,PARAM123,PARAM124,PARAM125,PARAM126)

%    This function was generated by the Symbolic Math Toolbox version 9.0.
%    22-Jan-2023 12:35:40

Dthetat = in2(5,:);
Dxt = in2(4,:);
Nc = in2(3,:);
YP86 = in3(1,:);
YP87 = in3(2,:);
YP89 = in3(4,:);
YP90 = in3(5,:);
theta = in2(2,:);
t2 = cos(theta);
t3 = sin(theta);
t4 = param123+param124;
t5 = Dthetat.^2;
t6 = Dxt.*Nc;
t8 = 1.0./param122;
t7 = sign(t6);
t9 = 1.0./t4;
eqs = [Nc.*1.0e+3-param121.*t4+param122.*param124.*(YP90.*t3+t2.*t5);YP90-(t8.*(-param121.*t3+t2.*(t9.*(param120+param122.*param124.*t5.*(t3+param125.*t2.*t7))-param121.*param125.*t7)+(Dthetat.*param126.*t8)./param124))./(param124.*t2.*t9.*(t2-param125.*t7)-4.0./3.0);YP89+t9.*(-param120+param122.*param124.*(YP90.*t2-t3.*t5)+Nc.*param125.*t7.*1.0e+3);Dxt-YP86;Dthetat-YP87];
