function eqs = craneDAEFunction(t,in2,in3,param164,param165,param166,param167,param168,param169,param170,param171,param172)
%craneDAEFunction
%    EQS = craneDAEFunction(T,IN2,IN3,PARAM164,PARAM165,PARAM166,PARAM167,PARAM168,PARAM169,PARAM170,PARAM171,PARAM172)

%    This function was generated by the Symbolic Math Toolbox version 9.0.
%    26-Jan-2023 12:19:22

Dthetat = in2(5,:);
Dxt = in2(4,:);
Nc = in2(3,:);
YP96 = in3(1,:);
YP97 = in3(2,:);
YP99 = in3(4,:);
YP100 = in3(5,:);
theta = in2(2,:);
t2 = sign(Dxt);
t3 = sign(Nc);
t4 = cos(theta);
t5 = sin(theta);
t6 = param168+param169;
t7 = Dthetat.^2;
t8 = 1.0./t6;
eqs = [Nc.*1.0e+3-param167.*t6+param165.*param169.*(YP100.*t5+t4.*t7);YP100+(param167.*t5-t4.*(t8.*(param164+param165.*param169.*t7.*(t5+param170.*t2.*t3.*t4))-param167.*param170.*t2.*t3)+(param165.^2.*param166.*param171.^2.*param172.*t7.*sign(Dthetat).*1.550313834014991e+1)./param169)./(param165.*(param169.*t4.*t8.*(t4-param170.*t2.*t3)-4.0./3.0));YP99+t8.*(-param164+param165.*param169.*(YP100.*t4-t5.*t7)+Nc.*param170.*t2.*t3.*1.0e+3);Dxt-YP96;Dthetat-YP97];
