function eqs = craneDAEFunction(t,in2,in3,param122,param123,param124,param125,param126,param127,param128,param129,param130)
%craneDAEFunction
%    EQS = craneDAEFunction(T,IN2,IN3,PARAM122,PARAM123,PARAM124,PARAM125,PARAM126,PARAM127,PARAM128,PARAM129,PARAM130)

%    This function was generated by the Symbolic Math Toolbox version 9.0.
%    25-Jan-2023 14:39:54

Dthetat = in2(5,:);
Dxt = in2(4,:);
Nc = in2(3,:);
YP76 = in3(1,:);
YP77 = in3(2,:);
YP79 = in3(4,:);
YP80 = in3(5,:);
theta = in2(2,:);
t2 = sign(Dxt);
t3 = sign(Nc);
t4 = cos(theta);
t5 = sin(theta);
t6 = param126+param127;
t7 = Dthetat.^2;
t8 = 1.0./t6;
eqs = [Nc.*1.0e+3-param125.*t6+param123.*param127.*(YP80.*t5+t4.*t7);YP80-(-param125.*t5+t4.*(t8.*(param122+param123.*param127.*t7.*(t5+param128.*t2.*t3.*t4))-param125.*param128.*t2.*t3)+(param123.^2.*param124.*param129.^2.*param130.*t7.*1.550313834014991e+1)./param127)./(param123.*(param127.*t4.*t8.*(t4-param128.*t2.*t3)-4.0./3.0));YP79+t8.*(-param122+param123.*param127.*(YP80.*t4-t5.*t7)+Nc.*param128.*t2.*t3.*1.0e+3);Dxt-YP76;Dthetat-YP77];
