function eqs = cartpoleDAEFunction(t,in2,in3,param162,param163,param164,param165,param166,param167,param168)
%cartpoleDAEFunction
%    EQS = cartpoleDAEFunction(T,IN2,IN3,PARAM162,PARAM163,PARAM164,PARAM165,PARAM166,PARAM167,PARAM168)

%    This function was generated by the Symbolic Math Toolbox version 9.0.
%    22-Jan-2023 17:25:14

Dthetat = in2(5,:);
Dxt = in2(4,:);
Nc = in2(3,:);
YP116 = in3(1,:);
YP117 = in3(2,:);
YP119 = in3(4,:);
YP120 = in3(5,:);
theta = in2(2,:);
t2 = cos(theta);
t3 = sin(theta);
t4 = param165+param166;
t5 = Dthetat.^2;
t6 = Dxt.*Nc;
t8 = 1.0./param164;
t7 = sign(t6);
t9 = 1.0./t4;
eqs = [Nc.*1.0e+3-param163.*t4+param164.*param166.*(YP120.*t3+t2.*t5);YP120-(t8.*(-param163.*t3+t2.*(t9.*(param162+param164.*param166.*t5.*(t3+param167.*t2.*t7))-param163.*param167.*t7)+(Dthetat.*param168.*t8)./param166))./(param166.*t2.*t9.*(t2-param167.*t7)-4.0./3.0);YP119+t9.*(-param162+param164.*param166.*(YP120.*t2-t3.*t5)+Nc.*param167.*t7.*1.0e+3);Dxt-YP116;Dthetat-YP117];
