% Simplify expressions


% Deriving linear approximations of CSTR model symbolically
clear

% Kinetic parameters
syms Z_Tc Z_Td Z_I Z_P Z_fm E_Tc E_Td E_I E_P E_fm

% Physical parameters
syms F V rho Tj Tin A f_star FI Fm Mm mDeltaHp cp U R

% Disturbances (inputs)
syms Ci_in Cm_in 

% State variables
syms Cm CI T D0 D1

% Sub-expressions
syms Zp_exp_Ep Zfm_exp_Efm  ZTd_exp_ETd  ZTc_exp_ETc  ZI_expEI  P0_CI

J = (Cm * E_fm * P0_CI * Zfm_exp_Efm) / (R*T^2) ...
        + (CI * E_I * ZI_expEI * f_star * (ZTc_exp_ETc + 2 * ZTd_exp_ETd)) ...
        / (R*T^2 * (ZTc_exp_ETc + ZTd_exp_ETd)) ...
        - (2 * CI * ZI_expEI * f_star * (E_Tc * ZTc_exp_ETc + E_Td * ZTd_exp_ETd) ...
           * (0.5 * ZTc_exp_ETc + ZTd_exp_ETd)) ...
        / (R*T^2 * (ZTc_exp_ETc + ZTd_exp_ETd)^2) ...
        + (CI * ZI_expEI * Z_Td * f_star * (E_Tc * ZTc_exp_ETc + 2 * E_Td * ZTd_exp_ETd)) ...
        / (R*T^2 * (ZTd_exp_ETd + ZTc_exp_ETc * Z_Td)) ...
        + (CI * Cm * ZI_expEI * Zfm_exp_Efm * f_star ...
           * (E_I * ZTc_exp_ETc + E_I * ZTd_exp_ETd - E_Tc * ZTc_exp_ETc - E_Td * ZTd_exp_ETd)) ...
        / (P0_CI * R*T^2 * (ZTc_exp_ETc + ZTd_exp_ETd)^2);